#!/usr/bin/perl

&main;

sub main
{
    my $make_file = "./Makefile";
    my $mk = "./mk";

    if ( ! -e $mk)
    {
        print STDERR "ERROR: can't find mk file. Aborted\n";
        exit -1;
    }
    

    print "writing Makefile...\n=================== NEW MAKEFILE ===================\n";
    open (MAKEFILE, ">", $make_file);
    open (MK, "<", $mk);

    print MAKEFILE "CC=gcc\n";
    print MAKEFILE "CFLAGS=-I.\n";
    print MAKEFILE "\$DEPS=\n";
    print MAKEFILE "\n";
    print MAKEFILE "all: ";

    my @prefixs;
    my $tgt_hash = {};
    while(<MK>)
    {
        chomp;
        my @files;
        next if ($_ =~ "#" );
        
        $_ =~ s/\s//g;
        @files = split (',', $_);
        foreach my $file (@files)
        {

            if ($file =~ "(.*)\.c")
            {
                my $prefix = "exe_".$1;
                my $file_name = $1;
                if ($file =~ "(.*)_src")
                {
                    $prefix = "exe_".$1;
                }

                if (! defined ($$tgt_hash{$prefix}) || $$tgt_hash{$prefix} eq "")
                {
                    $$tgt_hash{$prefix} = $file_name.".o";
                }
                else
                {
                    $$tgt_hash{$prefix} .= " ".$file_name.".o";
                }
            }
        }
    }
    foreach my $key ( keys %$tgt_hash )
    {
        print MAKEFILE $key." ";
    }
    print MAKEFILE "\n\n";
    print MAKEFILE "%.o: %.c \$(DEPS)\n\t\$(CC) -c -o \$@ \$< \$(CFLAGS)\n";
    print MAKEFILE "\n";
    foreach my $key ( keys %$tgt_hash )
    {
        print MAKEFILE "$key: $$tgt_hash{$key}\n\t\$(CC) -o \$@ \$^ \$(CFLAGS)\n\n";
    }



    print MAKEFILE "\nclean:\n";
    print MAKEFILE "\trm -rf ./*.o ./exe_*\n";

    close(MK);
    close(MAKEFILE);

    system ("cat $make_file");

}
