#!/usr/bin/perl

my ($src_file)= $ARGV[0];
my $prefix;

print "src file: $src_file\n";
if ($src_file =~ /(.*).c/)
{
    $prefix = $1;    

    print "prefix: $prefix\n";
}

&main;

sub main
{
    my $make_file = "./Makefile";
    my $temp= "./Makefile_tmp";

    print "execute main\n";
    open (MAKEFILE, "<", $make_file);
    open (TMP, ">", $temp);

    while(<MAKEFILE>)
    {
        next if ($_ =~ "clean" || $_ =~ "rm -rf");
        if ($_ =~ "all: (.*)")
        {
            chomp;
            $_ = $_."  exe_$prefix\n";
        }
        print TMP $_;
    }
    print TMP "exe_".$prefix.": "."$prefix".".o\n";
    print TMP "\tgcc -o \$@ \$^ \$(CFLAGS)\n \n";
    print TMP "clean:\n";
    print TMP "\trm -rf ./*.o ./exe_*\n";

    close(TMP);
    close(MAKEFILE);

    system ("cp $make_file $make_file".".bk");
    system ("cp $temp $make_file; rm $temp");
    system ("cat $make_file");

}
